[versions]
kotlin = "2.0.0"

[libraries.kotlin-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.kotlin-test-core]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test"

[libraries.kotlin-test-junit]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test-junit"

[libraries.android-gradle]
version = "8.2.0"
module = "com.android.tools.build:gradle"

[libraries.compose-gradle]
version = "1.5.12"
module = "org.jetbrains.compose:compose-gradle-plugin"

[libraries.dokka]
version = "1.9.10"
module = "org.jetbrains.dokka:dokka-gradle-plugin"

[libraries.kotlinx-binary-compatibility]
version = "0.13.2"
module = "org.jetbrains.kotlinx:binary-compatibility-validator"
