name: Latest Build
on:
    push:
        branches: [master]
jobs:
    tests:
        uses: inkapplications/.github/.github/workflows/kmp-checks.yml@1.1.0
    publish-site:
        name: Publish Site
        needs: [tests]
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            pages: write
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4.1.7
            -
                name: Configure Java
                uses: actions/setup-java@v4.2.1
                with:
                    java-version: 17
                    distribution: temurin
            -
                name: Build Static Sample
                run: ./gradlew sample-web:buildStatic sample-web:assemble
            -
                name: Create Deploy Directory
                run: |
                    mkdir -p build/pages
                    cp -r sample-web/build/static/* build/pages/
                    cp -r sample-web/build/dist/js/productionExecutable/* build/pages/
                    mv build/pages/sample.html build/pages/index.html
            -
                name: Upload Pages Artifact
                uses: actions/upload-pages-artifact@v3.0.1
                with:
                    path: build/pages
            -
                name: Deploy to GitHub Pages
                uses: actions/deploy-pages@v4.0.5
