name: Latest Build
on:
    push:
        branches: [master]
jobs:
    tests:
        uses: inkapplications/.github/.github/workflows/kmp-checks.yml@1.1.2
    publish-site:
        name: Publish Site
        needs: [tests]
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            pages: write
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4.2.2
            -
                name: Configure Java
                uses: actions/setup-java@v4.6.0
                with:
                    java-version: 17
                    distribution: temurin
            -
                name: Build Static Sample
                run: ./gradlew sample-web:distWeb
            -
                name: Upload Pages Artifact
                uses: actions/upload-pages-artifact@v3.0.1
                with:
                    path: sample-web/build/dist/web
            -
                name: Deploy to GitHub Pages
                uses: actions/deploy-pages@v4.0.5
