name: Release
on:
    push:
        tags: ['*']
jobs:
    tests:
        name: Test
        uses: inkapplications/.github/.github/workflows/kmp-checks.yml@1.2.0
    publish-site:
        name: Publish Site
        needs: [tests]
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            pages: write
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4.2.2
            -
                name: Configure Java
                uses: actions/setup-java@v4.7.1
                with:
                    java-version: 17
                    distribution: temurin
            -
                name: Build Static Sample
                run: bin/gradlew sample-web:distWeb
            -
                name: Upload Pages Artifact
                uses: actions/upload-pages-artifact@v3.0.1
                with:
                    path: sample-web/build/dist/web
            -
                name: Deploy to GitHub Pages
                uses: actions/deploy-pages@v4.0.5
    publish-maven:
        name: Publish to Maven Central
        needs: [tests]
        secrets: inherit
        uses: inkapplications/.github/.github/workflows/kmp-maven-publish.yml@1.2.0
        with:
            version: ${{ github.ref_name }}
            publish-android: true
            draft-release: false
    build-cli:
        name: Publish CLI
        needs: [tests]
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4.2.2
            -
                name: Configure Java
                uses: actions/setup-java@v4.7.1
                with:
                    java-version: 23
                    distribution: temurin
            -
                name: Create CLI Distribution
                run: bin/gradlew cli:distZip
            -
                name: Create Wrapper
                run: bin/create-wrapper ${{ github.ref_name }} $(sha256sum cli/build/distributions/inkui-${{ github.ref_name }}.zip | cut -d' ' -f1)
            -
                name: Create Release
                id: create_release
                uses: actions/create-release@v1.1.4
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: ${{ github.ref_name }}
                    draft: true
                    prerelease: false
            -
                name: Upload CLI Asset
                uses: actions/upload-release-asset@v1.0.2
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: cli/build/distributions/inkui-${{ github.ref_name }}.zip
                    asset_name: inkui-${{ github.ref_name }}.zip
                    asset_content_type: application/zip
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -
                name: Upload Wrapper Asset
                uses: actions/upload-release-asset@v1.0.2
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: cli/build/distributions/inkui-wrapper
                    asset_name: inkui-wrapper
                    asset_content_type: text/x-shellscript
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
